// <auto-generated />
using System;
using Epidemiologia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Epidemiologia.Migrations
{
    [DbContext(typeof(EpidemiologiaContext))]
    partial class EpidemiologiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enfermedad", b =>
                {
                    b.Property<int>("Id_enfermedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_enfermedad"));

                    b.Property<string>("Cod_enferemedad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_enfermedad");

                    b.ToTable("Enfermedad");
                });

            modelBuilder.Entity("Epidemiologia.Dominio.RegistroCaso", b =>
                {
                    b.Property<int>("Id_RegistroCaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_RegistroCaso"));

                    b.Property<string>("Cod_Caso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_enfermedad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_paciente")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id_RegistroCaso");

                    b.HasIndex("Id_enfermedad");

                    b.HasIndex("Id_paciente");

                    b.ToTable("RegistroCaso");
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.Property<int>("Id_paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_paciente"));

                    b.Property<string>("Cod_paciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_paciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("Epidemiologia.Dominio.RegistroCaso", b =>
                {
                    b.HasOne("Enfermedad", "Enfermedad")
                        .WithMany("RegistroCasos")
                        .HasForeignKey("Id_enfermedad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paciente", "Paciente")
                        .WithMany("RegistroCasos")
                        .HasForeignKey("Id_paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermedad");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Enfermedad", b =>
                {
                    b.Navigation("RegistroCasos");
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.Navigation("RegistroCasos");
                });
#pragma warning restore 612, 618
        }
    }
}
